// Seed-Daten für TempMatch.
// Diese Arrays sind die Ausgangsdaten, mit denen die Datenbank befüllt wird
// (siehe prisma/seed.ts). Zur Laufzeit liest die App aus der DB (src/lib/db.ts),
// nicht mehr aus dieser Datei. Die Domänen-Typen stehen in src/lib/types.ts.

import type {
  Agentur,
  Firma,
  Inserat,
  Kandidat,
} from "@/lib/types";

// Re-Export für Komponenten, die ihre Typen historisch von hier importieren.
export type {
  Agentur,
  Beruf,
  Firma,
  Inserat,
  InseratStatus,
  Kandidat,
  KandidatStatus,
} from "@/lib/types";

export const firmen: Firma[] = [
  {
    id: "f1",
    name: "Müller Bau AG",
    branche: "Baugewerbe",
    ort: "Zürich",
    kontaktperson: "Thomas Müller",
  },
  {
    id: "f2",
    name: "Gastro Genuss GmbH",
    branche: "Gastronomie",
    ort: "Winterthur",
    kontaktperson: "Sandra Keller",
  },
  {
    id: "f3",
    name: "LogiTrans Logistik",
    branche: "Logistik",
    ort: "Dietikon",
    kontaktperson: "Marco Bianchi",
  },
];

export const agenturen: Agentur[] = [
  {
    id: "a1",
    name: "FlexPersonal AG",
    ort: "Zürich",
    kontaktperson: "Petra Wyss",
    aboAktiv: true,
  },
  {
    id: "a2",
    name: "TempProfi Vermittlung",
    ort: "Baden",
    kontaktperson: "Daniel Frei",
    aboAktiv: true,
  },
];

export const inserate: Inserat[] = [
  {
    id: "i1",
    firmaId: "f1",
    titel: "Maler für Renovationsprojekt gesucht",
    beruf: "Maler",
    beschreibung:
      "Für ein grösseres Renovationsprojekt in Zürich-West suchen wir einen erfahrenen Maler. Innen- und Aussenarbeiten.",
    anforderungen: ["EFZ-Abschluss als Maler", "Mind. 3 Jahre Erfahrung", "Selbständiges Arbeiten"],
    ort: "Zürich",
    startDatum: "2026-06-15",
    dauer: "3 Wochen",
    festanstellungMoeglich: false,
    status: "OFFEN",
    erstelltAm: "2026-06-02",
  },
  {
    id: "i2",
    firmaId: "f1",
    titel: "Schreiner für Innenausbau",
    beruf: "Schreiner",
    beschreibung:
      "Innenausbau einer Bürofläche. Montage von Trennwänden, Einbaumöbeln und Türen.",
    anforderungen: ["EFZ Schreiner", "Erfahrung im Innenausbau", "Eigenes Werkzeug von Vorteil"],
    ort: "Zürich",
    startDatum: "2026-06-20",
    dauer: "2 Wochen",
    festanstellungMoeglich: false,
    status: "OFFEN",
    erstelltAm: "2026-06-03",
  },
  {
    id: "i3",
    firmaId: "f2",
    titel: "Koch für Sommersaison",
    beruf: "Koch",
    beschreibung:
      "Verstärkung für unsere Küche während der Sommersaison. À-la-carte Restaurant mit saisonaler Küche.",
    anforderungen: ["Kochlehre abgeschlossen", "Erfahrung à la carte", "Wochenendarbeit möglich"],
    ort: "Winterthur",
    startDatum: "2026-07-01",
    dauer: "2 Monate",
    festanstellungMoeglich: true,
    status: "OFFEN",
    erstelltAm: "2026-06-01",
  },
  {
    id: "i4",
    firmaId: "f3",
    titel: "Lagerist mit Staplerausweis",
    beruf: "Lagerist",
    beschreibung:
      "Für unser Logistikzentrum suchen wir einen zuverlässigen Lageristen. Kommissionierung und Wareneingang.",
    anforderungen: ["Staplerausweis (Kat. R)", "Körperliche Belastbarkeit", "Schichtbereitschaft"],
    ort: "Dietikon",
    startDatum: "2026-06-10",
    dauer: "1 Monat",
    festanstellungMoeglich: true,
    status: "OFFEN",
    erstelltAm: "2026-06-04",
  },
  {
    id: "i5",
    firmaId: "f3",
    titel: "Reinigungskraft für Bürogebäude",
    beruf: "Reinigungskraft",
    beschreibung:
      "Unterhaltsreinigung eines Bürogebäudes in den Abendstunden. Geregelte Arbeitszeiten.",
    anforderungen: ["Erfahrung in der Gebäudereinigung", "Zuverlässigkeit", "Abendarbeit (ab 18 Uhr)"],
    ort: "Dietikon",
    startDatum: "2026-06-12",
    dauer: "Unbefristet (temporär)",
    festanstellungMoeglich: false,
    status: "OFFEN",
    erstelltAm: "2026-06-04",
  },
];

export const kandidaten: Kandidat[] = [
  // Inserat i1 – Maler
  {
    id: "k1",
    inseratId: "i1",
    agenturId: "a1",
    vorname: "Andreas",
    nachname: "Huber",
    beruf: "Maler",
    erfahrungJahre: 8,
    qualifikationen: ["EFZ Maler", "Gerüstbau-Erfahrung", "Fahrausweis Kat. B"],
    verfuegbarAb: "2026-06-15",
    verfuegbarBis: "2026-09-15",
    telefon: "+41 79 123 45 67",
    email: "a.huber@example.com",
    status: "AUSSTEHEND",
    notiz: "Sehr zuverlässig, war bereits in mehreren Grossprojekten im Einsatz.",
  },
  {
    id: "k2",
    inseratId: "i1",
    agenturId: "a2",
    vorname: "Luka",
    nachname: "Petrović",
    beruf: "Maler",
    erfahrungJahre: 5,
    qualifikationen: ["EFZ Maler", "Tapezier-Spezialist"],
    verfuegbarAb: "2026-06-16",
    verfuegbarBis: "2026-09-16",
    telefon: "+41 76 234 56 78",
    email: "l.petrovic@example.com",
    status: "AUSSTEHEND",
    notiz: "Spezialisiert auf hochwertige Innenanstriche und Tapezierarbeiten.",
  },
  // Inserat i2 – Schreiner
  {
    id: "k3",
    inseratId: "i2",
    agenturId: "a1",
    vorname: "Marco",
    nachname: "Steiner",
    beruf: "Schreiner",
    erfahrungJahre: 12,
    qualifikationen: ["EFZ Schreiner", "CNC-Erfahrung", "Vorarbeiter"],
    verfuegbarAb: "2026-06-20",
    verfuegbarBis: "2026-12-20",
    telefon: "+41 78 345 67 89",
    email: "m.steiner@example.com",
    status: "AUSSTEHEND",
    notiz: "Langjährige Erfahrung im Innenausbau, kann auch ein Team führen.",
  },
  // Inserat i3 – Koch
  {
    id: "k4",
    inseratId: "i3",
    agenturId: "a1",
    vorname: "Sofia",
    nachname: "Rossi",
    beruf: "Koch",
    erfahrungJahre: 6,
    qualifikationen: ["Kochlehre EFZ", "Erfahrung Gourmetküche", "Allergen-Schulung"],
    verfuegbarAb: "2026-07-01",
    verfuegbarBis: "2026-09-30",
    telefon: "+41 79 456 78 90",
    email: "s.rossi@example.com",
    fruehererArbeitgeber: "Hotel Krone Winterthur",
    status: "AUSGEWAEHLT",
    notiz: "Kreativ, schnell, hervorragende Referenzen aus der gehobenen Gastronomie.",
  },
  {
    id: "k5",
    inseratId: "i3",
    agenturId: "a2",
    vorname: "Jonas",
    nachname: "Meier",
    beruf: "Koch",
    erfahrungJahre: 3,
    qualifikationen: ["Kochlehre EFZ", "à-la-carte Erfahrung"],
    verfuegbarAb: "2026-07-03",
    verfuegbarBis: "2026-08-31",
    telefon: "+41 76 567 89 01",
    email: "j.meier@example.com",
    status: "ABGELEHNT",
    notiz: "Junger, motivierter Koch mit solider Grundausbildung.",
  },
  // Inserat i4 – Lagerist
  {
    id: "k6",
    inseratId: "i4",
    agenturId: "a2",
    vorname: "Ahmed",
    nachname: "Yilmaz",
    beruf: "Lagerist",
    erfahrungJahre: 4,
    qualifikationen: ["Staplerausweis Kat. R", "Logistik-Grundkurs", "Schichterfahrung"],
    verfuegbarAb: "2026-06-10",
    verfuegbarBis: "2026-07-10",
    telefon: "+41 78 678 90 12",
    email: "a.yilmaz@example.com",
    fruehererArbeitgeber: "Migros Genossenschaft",
    status: "AUSSTEHEND",
    notiz: "Erfahren im Umgang mit Lagerverwaltungssystemen (SAP).",
  },
  // Inserat i5 – Reinigungskraft
  {
    id: "k7",
    inseratId: "i5",
    agenturId: "a1",
    vorname: "Maria",
    nachname: "Santos",
    beruf: "Reinigungskraft",
    erfahrungJahre: 7,
    qualifikationen: ["Gebäudereinigung", "Bodenpflege-Maschinen", "Referenzen vorhanden"],
    verfuegbarAb: "2026-06-12",
    verfuegbarBis: "2026-09-12",
    telefon: "+41 79 789 01 23",
    email: "m.santos@example.com",
    fruehererArbeitgeber: "ISS Facility Services AG",
    status: "AUSSTEHEND",
    notiz: "Sehr gründlich und zuverlässig, langjährige Unterhaltsreinigung.",
  },
];
