// Die 26 Schweizer Kantone (alphabetisch).
export const KANTONE = [
  "Aargau",
  "Appenzell Ausserrhoden",
  "Appenzell Innerrhoden",
  "Basel-Landschaft",
  "Basel-Stadt",
  "Bern",
  "Freiburg",
  "Genf",
  "Glarus",
  "Graubünden",
  "Jura",
  "Luzern",
  "Neuenburg",
  "Nidwalden",
  "Obwalden",
  "Schaffhausen",
  "Schwyz",
  "Solothurn",
  "St. Gallen",
  "Tessin",
  "Thurgau",
  "Uri",
  "Waadt",
  "Wallis",
  "Zug",
  "Zürich",
] as const;

// Berufsvorschläge für das Beruf-Suchfeld (freie Eingabe bleibt möglich).
export const BERUF_VORSCHLAEGE = [
  "Maler",
  "Schreiner",
  "Lagerist",
  "Koch",
  "Elektriker",
  "Reinigungskraft",
  "Maurer",
  "Zimmermann",
  "Gipser",
  "Sanitärinstallateur",
  "Service / Kellner",
  "Pflegefachperson",
  "Chauffeur",
  "Monteur",
] as const;
